name: Build PDFium WASM

on:
  workflow_dispatch:
    inputs:
      force_clean_cache:
        description: 'Force clean cache run (ignore all caches)'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile PDFium
      run: |
        cd /opt
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "/opt/depot_tools" >> $GITHUB_PATH
        export PATH="/opt/depot_tools:$PATH"
        mkdir -p /tmp/pdfium-build
        cd /tmp/pdfium-build
        gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git --custom-var checkout_configuration=minimal
        echo "target_os = [ 'emscripten' ]" >> .gclient
        gclient sync -r origin/chromium/7267 --no-history --shallow
        bash -x ./pdfium/build/install-build-deps.sh --no-prompt
