name: Build PDFium WASM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install Node.js (equivalent to node-setup stage)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    # Install Emscripten SDK
    - name: Cache Emscripten SDK
      uses: actions/cache@v4
      id: emsdk-cache
      with:
        path: /opt/emsdk
        key: emsdk-4.0.10-${{ runner.os }}
        restore-keys: |
          emsdk-4.0.10

    - name: Install Emscripten SDK
      if: steps.emsdk-cache.outputs.cache-hit != 'true'
      run: |
        cd /opt
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install 4.0.10
        ./emsdk activate 4.0.10

    # Install depot_tools (equivalent to depot-tools stage)
    - name: Cache depot_tools
      uses: actions/cache@v4
      id: depot-tools-cache
      with:
        path: /opt/depot_tools
        key: depot-tools-${{ runner.os }}
        restore-keys: |
          depot-tools

    - name: Install depot_tools
      if: steps.depot-tools-cache.outputs.cache-hit != 'true'
      run: |
        cd /opt
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git -b main depot_tools

    - name: Setup depot_tools
      run: |
        echo "/opt/depot_tools" >> $GITHUB_PATH
        export PATH="/opt/depot_tools:$PATH"

    # Get PDFium source (equivalent to pdfium-src stage)
    - name: Cache PDFium source
      uses: actions/cache@v4
      id: pdfium-cache
      with:
        path: /tmp/pdfium-build
        key: pdfium-src-chromium-7267
        restore-keys: |
          pdfium-src-chromium-7267
          pdfium-src-

    - name: Download PDFium source
      if: steps.pdfium-cache.outputs.cache-hit != 'true'
      run: |
        export PATH="/opt/depot_tools:$PATH"
        mkdir -p /tmp/pdfium-build
        cd /tmp/pdfium-build
        gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git --custom-var checkout_configuration=minimal
        echo "target_os = [ 'emscripten' ]" >> .gclient
        gclient sync -r origin/chromium/7267 --no-history --shallow

    # Install PDFium build dependencies (equivalent to pdfium-deps stage)
    - name: Install PDFium build dependencies
      run: |
        cd /tmp/pdfium-build
        bash -x ./pdfium/build/install-build-deps.sh --no-prompt
